services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
     - "8080:8080"
    command: start-dev
    networks:
      - kc-demo-network
    healthcheck:
      test: curl -f http://keycloak:8080/health || exit 1
      interval: 3s
      retries: 5
  keycloak-provisioner:
    image: quay.io/keycloak/keycloak:18.0.2
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - KEYCLOAK_SERVER=http://keycloak:8080
    volumes:
      - ./provisioning.sh:/provisioning.sh
    entrypoint: /provisioning.sh
    networks:
      - kc-demo-network
  server:
    build: ./server
    environment:
      - IAM_URL=http://keycloak:8080/realms/demo
    ports:
      - "9090:80"
    networks:
      - kc-demo-network
networks:
  kc-demo-network: